AWSTemplateFormatVersion: '2010-09-09'
Description: Main CloudFormation template that builds the glue crawlers and glue jobs related with the datalake
Parameters:
  applicationcode:
    Type: String
    Default: "cld0014001"
  projectname:
    Type: String
    Default: "cloudcenter"
  adminrolearn:
    Type: String
  dataengineerrolearn:
    Type: String
  environment:
    Type: String
    Default: "lab"
    AllowedValues:
      - "dev"
      - "lab"
      - "pdn"
  filial:
    Type: String
    Default: "bancolombia"
    AllowedValues:
      - "bancolombia"
      - "banistmo"
      - "bam"
      - "baes"
      - "nequi"
      - "corporativo"

Resources:
  
########################################################################################
# Crawler de Landing Conceptual
########################################################################################
  LandingCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Description : "Crawler to cloudcenter landing targets Conceptual"
      Name: 
        Fn::Sub: "${applicationcode}-${projectname}-${environment}-landing-crawler-conceptual"
      Role: 
        Fn::ImportValue: 
          Fn::Sub: "${applicationcode}-${projectname}-glue-role"
      DatabaseName: !Sub "cc_${environment}_${filial}_audit_db"
      Targets:
        S3Targets:
          - Path: !Sub "${applicationcode}-${projectname}-${environment}-${filial}-s3-landing/conceptual/"
#        DynamoDBTargets:
#          - Path: !Sub "${applicationcode}-${projectname}-${environment}-audit-table"
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "DELETE_FROM_DATABASE"

